#!/usr/bin/env bash

echo "load and unload working"
var_a=1
var_b=100

echo "BTUSB unmounted"
echo "Running ..."
while [ $var_a -lt 1000 ]
do
	sudo modprobe -r btusb 
	sudo modprobe btusb
	((var_a=var_a+1))
done

echo "BTUSB mounted"


